### ISSUE TITLE
Discrepancy in requires-dist Metadata between PyPi and  pyproject.toml

### ISSUE THREAD

**Issue by robsidiii** [hynek/argon2-cffi-bindings#66]
Hi,
I noticed that the requires-dist field is set to null in the PyPI JSON API for the package argon2-cffi-bindings (https://pypi.org/pypi/argon2-cffi-bindings/json) but in the pyproject.toml file and unzipped wheel's metadata there is a dependancy ( cffi>=1.0.1) listed

**Comment by hynek** [comment]
I have downloaded https://files.pythonhosted.org/packages/ed/55/f8ba268bc9005d0ca57a862e8f1b55bf1775e97a36bd30b0a8fb568c265c/argon2_cffi_bindings-21.2.0-pp38-pypy38_pp73-win_amd64.whl to double-check and it's METADAT file says `Requires-Dist: cffi (>=1.0.1)` so I don't think this is my fault.

Either it's a bug on the PyPI side, or they haven't backfilled that data yet.
